//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZAdmin_DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fb_comentarios
    {
        public long idcomentario { get; set; }
        public string idfacebook { get; set; }
        public long idpost { get; set; }
        public string postagem { get; set; }
        public System.DateTime datahora { get; set; }
        public long curtidas { get; set; }
        public Nullable<long> respostas { get; set; }
        public string idcomentarioresposta { get; set; }
        public string urlimagem { get; set; }
        public string nomeimagem { get; set; }
        public string nomeusuario { get; set; }
        public string idusuario { get; set; }
        public bool termoscapturados { get; set; }
    
        public virtual fb_posts fb_posts { get; set; }
    }
}
