//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZAdmin_DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class noticias
    {
        public noticias()
        {
            this.noticias_empresa = new HashSet<noticias_empresa>();
            this.promo_promonoticias = new HashSet<promo_promonoticias>();
            this.noticia_imagens = new HashSet<noticia_imagens>();
        }
    
        public int idnoticia { get; set; }
        public int idfonte { get; set; }
        public Nullable<int> idnoticia_knewin { get; set; }
        public string titulo { get; set; }
        public string subtitulo { get; set; }
        public string dominio { get; set; }
        public string autor { get; set; }
        public string conteudo { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> datapublicacao { get; set; }
        public Nullable<System.DateTime> datacaptura_knewin { get; set; }
        public Nullable<System.DateTime> datacaptura_zeeng { get; set; }
        public string categoria { get; set; }
        public string localidade { get; set; }
        public string linguagem { get; set; }
        public Nullable<bool> excluido { get; set; }
        public Nullable<bool> termoscapturados { get; set; }
    
        public virtual fontes_noticias fontes_noticias { get; set; }
        public virtual ICollection<noticias_empresa> noticias_empresa { get; set; }
        public virtual ICollection<promo_promonoticias> promo_promonoticias { get; set; }
        public virtual ICollection<noticia_imagens> noticia_imagens { get; set; }
    }
}
